spring:
  application:
    name: istore-api
  mongodb:
    uri: mongodb://localhost:27017/istore_db

server:
  port: 8081

jwt:
  secret: aVeryLongSecretKeyForDevOnlyChangeThisInProduction1234567890
  expiration-ms: 900000
